<?php

return [
    'actions'              => 'Aktionen',
    'save'                 => 'Speichern',
    'created'              => 'Erstellt',
    'updated'              => 'Aktualisiert',
    'show'                 => 'Anzeigen',
    'edit'                 => 'Editieren',
    'delete'               => 'Löschen',
    'create_type'          => ':type erstellen',
    'edit_type'            => ':type editieren',
    'created_successful'   => ':type wurde erstellt',
    'created_error'        => 'Fehler beim erstellen des :type',
    'updated_successful'   => ':type wurde aktualisiert',
    'updated_error'        => 'Fehler beim aktualisieren des :type',
    'destroyed_successful' => ':type wurde gelöscht',
    'destroyed_error'      => 'Fehler beim Löschen des :type',
    'administration_type'  => ':type verwalten',
    'title'                => 'Titel',
    'slug'                 => 'Pfad',
    'url'                  => 'Url',
    'body'                 => 'Inhalt',
    'name'                 => 'Name',
    'unauthorized_access'  => 'Unautorisierter Zugriff',
    'class'                => 'Klasse',
    'link'                 => 'Link',
    'href'                 => 'Href',
    'rel'                  => 'Rel',
    'target'               => 'Target',
    'text'                 => 'Text',
    'file'                 => 'Datei',
    'alt'                  => 'Alt',
    'filename'             => 'Dateiname',
    'active'             => 'Aktiv',
    'user'             => 'Benutzer',
    'category'             => 'Kategorie',
];
