<?php

return [
    'actions' => 'Actions',
    'save' => 'Save',
    'created' => 'Created',
    'updated' => 'Updated',
    'show' => 'Show',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'create_type' => ':type create',
    'edit_type' => ':type edit',
    'created_successful' => ':type was created',
    'created_error' => 'Error on create :type',
    'updated_successful' => ':type was updated',
    'updated_error' => 'Error on edit:type',
    'destroyed_successful' => ':type was deleted',
    'destroyed_error' => 'Error on delete :type',
    'administration_type' => ':type administration',
    'title' => 'Title',
    'slug' => 'Slug',
    'url' => 'Url',
    'body' => 'Body',
    'name' => 'Name',
    'unauthorized_access' => 'Unauthorized access',
    'class' => 'Class',
    'link' => 'Link',
    'href' => 'Href',
    'rel' => 'Rel',
    'target' => 'Target',
    'text' => 'Text',
    'file' => 'File',
    'alt' => 'Alt',
    'filename' => 'Filename',

];
