language: php

sudo: true

php:
  - 7.0

env:
  - LARAVEL_VERSION="5.1.*" TESTBENCH_VERSION="3.1.*"
  - LARAVEL_VERSION="5.2.*" TESTBENCH_VERSION="3.2.*"
  - LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pngquant gifsicle jpegoptim

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" laravel/framework:"$LARAVEL_VERSION"
  - composer install

script: phpunit --coverage-text
