language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - LARAVEL_VERSION="5.1.*" TESTBENCH_VERSION="3.1.*"
  - LARAVEL_VERSION="5.2.*" TESTBENCH_VERSION="3.2.*"
  - LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*"

matrix:
  allow_failures:
  - env: LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pngquant gifsicle jpegoptim

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" laravel/framework:"$LARAVEL_VERSION"
  - composer install

script: phpunit --coverage-text

sudo: true
