<ul class="block-list">
    @if(view()->exists('page::cmf.menu'))
        @include('page::cmf.menu')
    @endif
    @if(view()->exists('gallery::cmf.menu'))
        @include('gallery::cmf.menu')
    @endif
    @if(view()->exists('user::cmf.menu'))
        @include('user::cmf.menu')
    @endif
    @if(view()->exists('video::cmf.menu'))
        @include('video::cmf.menu')
    @endif
    @if(view()->exists('block::cmf.menu'))
        @include('block::cmf.menu')
    @endif
    @if(view()->exists('menu::cmf.menu'))
        @include('menu::cmf.menu')
    @endif
    @if(view()->exists('forum::cmf.menu'))
        @include('forum::cmf.menu')
    @endif
    @if(view()->exists('email::cmf.menu'))
        @include('email::cmf.menu')
    @endif
</ul>